spring:
    security:
        oauth2:
            client:
                registration:
                    github:
                        client-id: Iv1.eda97a2f8ec6c553
                        client-secret: 3aec1599cf625aa1398fc7088f9d765950675a01

    data:
        cassandra:
            keyspace-name: main
            username: PvpcZNvkMeUbBMSDfgWBcTfB
            password: 9lSaD9Q4gDcomrSPbDqFKbGak_JvaEkCAtCdUdW8m-PzXleoQFOqCdR-ZtNz3J1-wEf7vlbu4CBr,915GR,WzUzFR9cypXQQNtYxmGDySk29yFg.n.,AJrATF36_sBU1
            schema-action: create-if-not-exists
            request:
                timeout: 10s
            connection:
                connect-timeout: 10s
                init-query-timeout: 10s

            
    main:
        allow-circular-references: true
        
astra.db:
    id: 047ab932-82ac-4fd2-8c56-2783ab8207c7-1
    region: europe-west1
    keyspace: main
    application.token: AstraCS:PvpcZNvkMeUbBMSDfgWBcTfB:b37bb4ce818822ccc7c464453b273ba03eda31caabe48ce4154bfe1aa9d37e5c
    
datastax.astra:
    secure-connect-bundle: secure-connect-inboxapi.zip

